### ISSUE TITLE
Mít víc receptů

### ISSUE THREAD

**Issue by hroncok** [hroncok/receptar#2]
Jeden recept je málo. Je potřeba jich mít určitě aspoň deset.
Nemůžeme ale krást recepty z internetu, protože na ně nemáme právo, musíme psát recepty z hlavy.

**Comment by zorinek** [comment]
Recept na buchtu si beru :D

**Comment by zuzanaDA** [comment]
Super projekt, přidám recept na špagety s kečupem!

**Comment by MikiPinkipie** [comment]
Paráda, přidám recept na sekerkovou polévku. :)

**Comment by hecvoj** [comment]
Ja budu dělat recept na vajíčkovou pomazánku. :D

**Comment by luipenox** [comment]
Přidám recept na uleželé olomoucké syrečky!

**Comment by PetrK9** [comment]
Přidám recept na Rajskou plévku.

**Comment by pet-a** [comment]
Dal by si někdo zabíjačkovou polévku? :D

**Comment by MarijaAP** [comment]
Přidám recept na caj s citronem

**Comment by petra-serisova** [comment]
pridám recept na raw dortík

**Comment by samuelbencak** [comment]
Luxusní nápad. Přidávání receptů je důležitá činnost. Jdu vypracovat recept na kuřecí maso s kari omáčkou za použití žehličky.

**Comment by stehlikovak** [comment]
přidám recept na výbornou pomazánku - sloní žrádlo

**Comment by IvcaJelinkova** [comment]
Super projekt. :-) Přidám ti do něj svůj rodinný recept na skvělé lívance. :-)

**Comment by tereziaskalova** [comment]
Pridam recept na prave slovenske halusky s bryndzov, pretoze som v CR este ziadne dobre nenasla.

**Comment by super-kachna** [comment]
Nahodím recept na Martini podle britských gentlemanů...

**Comment by ehanoj** [comment]
Mam recept na basniku!

**Comment by petr-bartusek** [comment]
Luxisní sushi po česku nechte na mě =)
https://recepty.vareni.cz/levne-sushi-po-cesku/

**Comment by kpapezova** [comment]
pridam recept na palacinky :)

**Comment by zorzo** [comment]
Přidám, recept na škubané placky.

**Comment by ZochovaS** [comment]
Co takhle pikantní rajčatová salsa? ;-)

**Comment by kpernica** [comment]
vajíčko natvrdo

**Comment by RobkooCZ** [comment]
treba na vodu ze stavou ??
