### ISSUE TITLE
Čaj s citrónem je v kořenovém adresáři.

### ISSUE THREAD

**Issue by samuelbencak** [hroncok/receptar#23]
Čaj s citrónem je v kořenovém adresáři.
Mám tušení, že recept caj-s-citronem patří do složky recepty.

**Comment by hroncok** [comment]
Spravíš to prosím?

**Comment by samuelbencak** [comment]
pokusím se o to

**Comment by samuelbencak** [comment]
Přesunuto do složky recepty.
